# Czech
[addon]
appDesc = '''Stahování videí z webu.'''
restore_purchase_button = '''Obnovit nákup'''
get_premium_button = '''Získat prémium'''
back = '''Zpět'''
rm_notifications_all = '''Smazat všechna oznámení'''
waiting_for_media = '''Čekám na médie'''
nomedia_title = '''Nevidíte média, která hledáte?'''
nomedia_description = '''Spusťte video (a přeskočte případné reklamy), abyste ulehčili detekci médií. Případně reportujte chybějící média.'''
nomedia_reload_button = '''Vynutit detekci'''
nomedia_reload_button_tooltip = '''Vynutit znovunačtení stránky (smazání cookies)'''
show_nomedia_button = '''Žádné video?'''
show_nomedia_button_tooltip = '''Klikněte zde, pokud nemůžete najít vaše video'''
setting_button_tooltip = '''Nastavení'''
history_button_tooltip = '''Zobrazit historii stahování'''
show_all_history_button = '''zobrazit všechno'''
complete_title = '''Hotovo'''
hide_complete_button = '''Skrýt'''
translate_button_tooltip = '''Pomozte s překladem VDH'''
open_source_tab_button_tooltip = '''Otevřít záložku se zdrojovým kódem'''
retry_download_button_tooltip = '''Opakovat stahování'''
delete_file_button_tooltip = '''Smazat soubor'''
download_directory_button_tooltip = '''Zobrazit stahovací složku'''
clear_downloaded_tooltip = '''Smazat dokončená stahování'''
show_in_popup_button_tooltip = '''Zobrazit v popup okně'''
show_in_sidebar_button_tooltip = '''Zobrazit v bočním panelu'''
video_not_playing_button_tooltip = '''Video se nepřehrává?'''
play = '''Přehrát'''
warn_drm_tooltip = '''Detekována ochrana DRM'''
version_title = '''Verze'''
account_title = '''Účet'''
one_hundred_downloads_title = '''Stáhl jste 100 videí!'''
leave_review_description = '''Jsme rádi, že si užíváte Video DownloadHelper :) Nechtěl byste napsat hezkou recenzi na stránkách obchodu s addony? '''
leave_review_button = '''Zanechat recenzi'''
account_status = '''Status'''
account_status_premium = '''Prémium (1$)'''
free_account = '''Zdarma'''
copy_to_clipboard = '''Kopírovat informace do schránky'''
my_account_button = '''Můj účet'''
download_title = '''Stahování'''
show_notification = '''Změnit nastavení'''
max_parallel_downloads = '''Maximální počet souběžných stahování'''
saveas_detected_warning = '''Všimli jsme si, že váš prohlížeč zobrazuje dialog 'Uložit jako', když se dokončí stahování. Doporučujeme zakázat tuto možnost v nastavení vašeho prohlížeče'''
change_saveas_setting = '''Změnit nastavení'''
private_browsing_title = '''Soukromé procházení'''
private_browsing_warning = '''Video DownloadHelper není povolen v soukromých/anonymních oknech. Musíte to povolit ručně (není vyžadováno).'''
private_browsing_notifications = '''Zobrazit oznámení pro soukromá stahování'''
private_browsing_button = '''Změnit nastavení soukromého procházení'''
throttle_youtube = '''Throttlovat YouTube (pomalejší stahování, ale menší pravděpodobnost zablokování)'''
prefer_original_audio = '''Upřednostnit původní zvuk'''
prefer_hls = '''Upřednostnit HLS'''
settings_history_title = '''Historie'''
transient_history_description = '''Zobrazit dokončená stahování v panelu'''
history_limit = '''Zapomenout historii stahování po X dnech'''
appearance_title = '''Přizpůsobení'''
theme_title = '''Téma'''
theme_light = '''světlé'''
theme_dark = '''tmavé'''
theme_system = '''systémové'''
popup_size_title = '''Velikost okna'''
popup_size_small = '''Malé'''
popup_size_medium = '''Střední'''
popup_size_big = '''Velké'''
panel_position_title = '''Umístění panelu'''
use_popup = '''Zobrazit ve vyskakovacím okně'''
use_sidebar = '''Zobrazit v bočním panelu'''
behavior_title = '''Chování'''
controls_title = '''Ovládání'''
show_in_context_menu = '''Umožnit ovládání z kontextové nabídky'''
restart_addon = '''Znovu načíst addon'''
reset_settings = '''Reset nastavení'''
prefered_quality = '''Upřednostňovaná kvalita videa'''
prefered_quality_highest = '''Nejvyšší (pomalé stahování, vysoké rozlišení)'''
prefered_quality_1080p = '''1080p (slušné výchozí)'''
prefered_quality_720p = '''720p (rychlé stahování, nízké rozlišení)'''
prefer_mkv = '''Pokud možno stáhnout jako MKV'''
preview_mode_title = '''Náhled média'''
preview_mode_none = '''Zakázáno'''
preview_mode_video = '''Krátký náhled'''
preview_mode_image = '''Obraz'''
history_title = '''Historie stahování'''
history_warning = '''Nezaznamenáváme vaši historii stahování. Chcete, aby si Video DownloadHelper pamatoval vaši historii stahování?'''
history_warning_2 = '''Buďte v klidu, všechno zůstává na vašem počítači. Ceníme si vašeho soukromí.'''
enable_history = '''Povolit historii'''
clear_history = '''Vymazat historii'''
disable_history = '''Nezaznamenávat historii'''
no_downloads_yet = '''Zatím žádné záznamy'''
download_failed = '''Stahování selhalo'''
download_failed_description = '''Bohužel se nepodařilo stáhnout specifické médium. Snažíme se o podporu co nejvíce webových stránek, proto velmi pomůže, pokud nahlásíte toto selhání (je to anonymní!).'''
download_interrupted = '''Stahování přerušeno'''
download_interrupted_description = '''Během stahování souboru došlo k problému se sítí, takže soubor může být kratší, než očekáváte. Snažíme se o podporu co nejvíce webových stránek, proto velmi pomůže, pokud nahlásíte toto selhání (je to anonymní!).'''
download_with_drm_failed_description = '''Něco se nepovedlo. Myslíme, že toto video má ochranu DRM. Nepodporujeme videa s DRM.'''
no_youtube = '''Stahování z YouTube není povoleno'''
no_youtube_description = '''Bohužel Chrome Web Store nepovoluje rozšíření, která stahují YouTube videa, takže jsme nemohli tuto možnost do verze pro Chrome vložit.'''
no_youtube_description_2 = '''Prosím použijte Firefox nebo Microsoft Edge'''
premium_required = '''Požadováno prémium'''
premium_yt_required_description = '''Bez prémium statusu musíte počkat 2 hodiny do dalšího stahování.'''
premium_hls_required_description = '''Bez prémium statusu mohou být HLS a MPD stahování prováděna nejdříve po 2 hodinách po skončení předchozího stahování.'''
youtube_too_many_downloads = '''Kua, zdá se, že YouTube vás blokuje.'''
youtube_too_many_downloads_description = '''YouTube občas omezuje počet požadovaných videí. Je to smutné, ale nic s tím nemůžeme udělat. Zkuste to znovu později.'''
stop = '''Stop'''
cancel = '''Zrušit'''
copy_url = '''Skopírovat adresu'''
always_copy_url = '''Vždy kopírovat adresu'''
download_button = '''Stáhnout'''
download_as_button_and_menu = '''Stáhnout jako...'''
rename_short = '''Přejmenovat'''
always_download_as_menu = '''Vždy stáhnout jako...'''
download_audio_button = '''Zvuk'''
download_audio_and_video_menu = '''Stáhnout zvuk a video'''
download_audio_only_menu = '''Stáhnout zvuk'''
audio_only_for_this_website = '''Vždy pouze zvuk pro tuto stránku'''
details = '''Detaily'''
report = '''Report'''
reporting = '''Reportování...'''
reported_thankyou = '''Dekujeme!'''
not_playing_title = '''Video se nepřehrává?'''
not_playing_broken_title = '''Poškozený zvuk nebo video?'''
not_playing_broken_description = '''Nahlašte poškozená média. Uděláme vše, co bude v našich silách, abychom to vyřešili (adresu videa posíláte anonymně - nesledujeme vás!)'''
not_playing_broken_solution_title = '''Vyzkoušejte moderní přehrávač videa'''
not_playing_broken_solution_windows_1 = '''Doporučujeme VLC:'''
not_playing_broken_solution_mac_1 = '''Doporučujeme IINA:'''
not_playing_broken_solution_2 = '''je to moderní, bezpečné a open source'''
not_playing_default_player = '''Ověřte, že váš přehrávač videa je nastaven jako výchozí v systému'''
not_playing_default_player_solution_windows = '''Ve Windows v 'Ovládacích panelech' klikněte na 'Výchozí aplikace' a změňte výchozí aplikaci pro přehrávač.'''
not_playing_default_player_solution_mac = '''Otevřete složku pro stahování kliknutím pravého tlačítka na soubor. Klikněte na 'Získat informace'. V 'Otevřít v...' sekci vyberte IINA. Klikněte na tlačítko 'Změnit vše'.'''

[web]
back = '''Zpět'''
header_help = '''Pomoc'''
activate_title = '''Aktivace'''
activate_pending = '''Čekání...'''
activate_success = '''Úspěch'''
activate_error = '''Chyba'''
activate_no_addon_found = '''Rozšíření nenalezeno. Je rozšíření instalováno?'''
activate_no_method_found = '''Metoda nenalezena.'''
activate_help_me = '''Pomozte mi.'''
issue_title = '''Obnovuji nákup'''
issue_submit = '''Odeslat'''
issue_thank_you = '''Děkujeme'''
issue_enter_email = '''Pro obnovení nákupu zadejte e-mailovou adresu použitou pro nákup licence:'''
issue_email_sent = '''Právě jsme vám odeslali e-mail s odkazem pro aktivaci prosuktu.'''
issue_or_digit = '''Případně můžete zadat 6místný kód, který jsme vám poslali:'''
issue_just_digit = '''Zadejte 6místný kód, který jsme vám poslali:'''
issue_i_have_a_code = '''(Klikněte zde, pokud už máte kód)'''
issue_i_have_a_key = '''(Klikněte zde, pokud už máte licenční klíč)'''
issue_key = '''Zadejte licenční klíč k Video DownloadHelperu:'''
landing_text1 = '''Stahujte jakékoliv videa odkudkoliv, prostě to funguje!'''
landing_text2 = '''Podporujeme více než 1000 stránek'''
landing_text3 = '''Důvěřuje nám 7 miliónů uživatelů'''
landing_text4 = '''Hodnocení 4,5 hvězdy v obchodě'''
landing_install_for_google = '''Instalovat do Chromu'''
landing_install_for_mozilla = '''Instalovat do Firefoxu'''
landing_install_for_microsoft = '''Instalovat do Edge'''
landing_feature1_title = '''Stahujte HD plnou rychlostí'''
landing_feature1_description = '''Stahujte videa ve vysokém rozlišení maximální rychlostí. Jsme hrdí na to, že můžeme tvrdit, že máme nejrychlejší stahovací engine na trhu.'''
landing_feature2_title = '''Archivovat videa'''
landing_feature2_description = '''Archivujte oblíbená videa, abyste se ujistili, že o nic nepřijdete.'''
landing_feature3_title = '''Podpora živého přenosu'''
landing_feature3_description = '''užijte si offline sledování živých streamů, osvoboďte se od real-time omezení.'''
landing_feature4_title = '''Stahování zvuku'''
landing_feature4_description = '''Extrahovat zvuk z videí, konvertovat je do MP3 nebo podcastů pro snadný poslech.'''
premium_hero1 = '''Zaplať jednou, používej navždy'''
premium_hero2 = '''Získejte doživotní licenci pro Video DownloadHelper'''
premium_hero3 = '''Stahujte kolik videí chcete, bez limitu.'''
welcome_text = '''Nyní nepropásnete žádné video.'''
welcome_pin_message = '''Připněte addon na toolbar:'''
