# Spanish

[addon]

# Video DownloadHelper description. 132 characters max.
appDesc = "Descargar videos de la web."

# Global strings
restore_purchase_button = "Restaurar compra"
get_premium_button = "Ir a premium"
back = "Atr√°s" # Go back button - in Settings panel for example

# Strings for the main panel
waiting_for_media = "Esperando medios‚Ä¶"
nomedia_title = "¬øNo ve el medio que est√° buscando?"
nomedia_description = "Inicie el video (y omita los anuncios, si los hay) para ayudar a detectar el medio. O informe que faltan medios."
nomedia_reload_button = "Forzar detecci√≥n"
nomedia_reload_button_tooltip = "Forzar recarga de p√°gina (borrar cookies)"
show_nomedia_button = "¬øNo hay video?"
show_nomedia_button_tooltip = "Haga clic aqu√≠ si no encuentra su video."
setting_button_tooltip = "Ajustes"
history_button_tooltip = "Mostrar historial de descargas"
translate_button_tooltip = "Ayudar a traducir VDH"

# Downloaded media box
open_source_tab_button_tooltip = "Abrir pesta√±a de c√≥digo"
retry_download_button_tooltip = "Reintentar descarga"
delete_file_button_tooltip = "Eliminar archivo"
download_directory_button_tooltip = "Mostrar directorio de descargas"
show_in_popup_button_tooltip = "Mostrar en ventana emergente"
show_in_sidebar_button_tooltip = "Mostrar en la barra lateral"
video_not_playing_button_tooltip = "¬øNo se reproduce el video?"
play = "Reproducir"
warn_drm_tooltip = "Se ha detectado DRM"

# Strings for the settings panel.
version_title = "Versi√≥n"
account_title = "Cuenta"
leave_review_description = "Hola ü§ö Video DownloadHelper es de uso gratuito. ¬øLe importar√≠a dejar una buena rese√±a? Me ser√≠a de gran ayuda üòä."
leave_review_button = "Dejar una rese√±a"
account_status= "Estado"
account_status_premium = "Premium ($1)" # $1 is the store (Mozilla, Google, Microsoft, All)
free_account = "Plan gratuito"
copy_to_clipboard = "Copiar informaci√≥n al portapapeles"
my_account_button = "Mi cuenta"
download_title = "Descargas"
show_notification = "Mostrar notificaci√≥n una vez completada la descarga"
max_parallel_downloads = "Descargas simult√°neas m√°ximas"
change_download_directory = "Cambiar directorio de descargas"

private_browsing_title = "Navegaci√≥n privada"
private_browsing_warning = "Video DownloadHelper no est√° habilitado en la navegaci√≥n privada."
private_browsing_notifications = "Mostrar notificaci√≥n para descargas privadas"
private_browsing_button = "Cambiar configuraci√≥n de navegaci√≥n privada"
prefer_original_audio = "Preferir audio original" # Firefox only
prefer_hls = "Preferir HLS" # Firefox only
settings_history_title = "Historial"
history_description = "Recordar descargas"
history_limit = "D√≠as antes de olvidar las descargas"
appearance_title = "Apariencia"
theme_title = "Tema"
theme_light = "Tema claro"
theme_dark = "Tema oscuro"
theme_system = "Tema del sistema"
popup_size_title = "Tama√±o de la ventana"
popup_size_small = "Peque√±o"
popup_size_medium = "Mediano"
popup_size_big = "Grande"
panel_position_title = "Posici√≥n del panel"
use_popup = "Usar ventana emergente"
use_sidebar = "Usar barra lateral"
behavior_title = "Comportamiento"
show_in_context_menu = "Mostrar men√∫ de descarga en el men√∫ contextual de la p√°gina"
restart_addon = "Reiniciar complemento"
reset_settings = "Restablecer ajustes"
prefer_highest_quality = "Seleccionar la calidad m√°s alta disponible en lugar de 1080p por defecto (descarga m√°s lenta, mayor calidad)."

# String for history page
history_title = "Historial de descargas"
history_warning = "No registramos su historial de descargas. ¬øDesea que Video DownloadHelper recuerde su historial de descargas?"
history_warning_2 = "No se preocupe, todo permanece en su equipo. Valoramos su privacidad."
enable_history = "Habilitar historial"
clear_history = "Borrar historial"
disable_history = "Deshabilitar historial"
no_downloads_yet = "A√∫n no hay descargas."

# Various notifications
download_failed = "Descarga fallida"
download_failed_description = "Algo no ha funcionado. Informe del error y haremos todo lo posible por averiguar por qu√© ha fallado (enviamos la URL del video de forma an√≥nima, ¬°no lo rastreamos!)."
download_with_drm_failed_description = "Algo no ha funcionado. Creemos que este video tiene DRM. No admitimos videos con DRM."
no_youtube = "No se permite la descarga desde YouTube"
no_youtube_description = "Lamentablemente, Chrome Web Store no permite que las extensiones descarguen videos de YouTube. Otros navegadores como Firefox no tienen esta limitaci√≥n."
premium_required = "Se requiere el estado Premium"
premium_yt_required_description = "Sin el estado Premium, solo se puede realizar una descarga de YouTube dos horas despu√©s de la anterior."
premium_required_description = "Sin el estado Premium, solo se puede realizar una descarga HLS dos horas despu√©s de la anterior."
v9_key_migration_failed_title = "Error al actualizar la licencia"
v9_key_migration_failed_description = "Estamos teniendo problemas para actualizar su licencia. Intente restaurar su compra."

# Downloading media box
stop = "Detener" # For HLS downloads
cancel = "Cancelar" # For HTTP downloads

# Media we found in the page
copy_url = "Copiar URL" # In menu and as a button
always_copy_url = "Copiar siempre la URL"
download_button = "Descargar"
download_audio_button = "Audio"
download_audio_and_video_menu = "Descargar audio y video"
download_audio_only_menu = "Descargar solo audio"
audio_only_for_this_website = "Siempre solo audio para este sitio web."
details = "Detalles"
more_settings = "M√°s ajustes‚Ä¶"

# Report buttons
report = "Informar"
reporting = "Informando‚Ä¶"
reported = "Informado"

# Video not playing - page
not_playing_title = "¬øNo se reproduce el video?"
not_playing_broken_title = "¬øEl audio o el video no funcionan?"
not_playing_broken_description = "Informe del fallo del medio. Haremos todo lo posible por averiguar por qu√© ha fallado (enviamos la URL del video de forma an√≥nima, ¬°no lo rastreamos!)."
not_playing_broken_solution_title = "Pruebe un reproductor de video moderno"
not_playing_broken_solution_windows_1 = "Recomendamos VLC:"
not_playing_broken_solution_mac_1 = "Recomendamos IINA:"
not_playing_broken_solution_2 = "es moderno, seguro y de C√≥digo abierto."
not_playing_default_player = "Aseg√∫rese de que su reproductor de video est√° configurado como reproductor predeterminado del sistema"
not_playing_default_player_solution_windows = "En el \‚ÄúPanel de control\‚Äù de Windows, haga clic en \‚ÄúProgramas predeterminados\‚Äù y cambie los programas predeterminados para su reproductor."
not_playing_default_player_solution_mac = "Abra el directorio de descargas y haga clic con el bot√≥n derecho del mouse en el archivo de video. Haga clic en ‚ÄúObtener informaci√≥n‚Äù. En la secci√≥n ‚ÄúAbrir con‚Äù, seleccione IINA. Haga clic en el bot√≥n ‚ÄúCambiar todo‚Äù."

[web]

# On top of all pages.
header_help = "Ayuda"
header_community = "Comunidad"

# Context: activation page after receiving the magic link via email.
activate_title = "Activaci√≥n" # hope it crashes
activate_pending = "Pendiente‚Ä¶"
activate_success = "√âxito"
activate_error = "Error"
activate_no_addon_found = "No se ha encontrado ning√∫n complemento. ¬øEst√° instalado el complemento?"
activate_no_method_found = "No se ha encontrado ning√∫n m√©todo."
activate_help_me = "Ayuda"

# Context: webpage to restore a purchase, which require the user to enter their email.
issue_title = "Restaurar compra"
issue_submit = "Enviar"
issue_thank_you = "Gracias"
issue_enter_email = "Para restaurar su compra, introduzca la direcci√≥n de correo electr√≥nico que utiliz√≥ para comprar su licencia:"
issue_email_sent = "Le acabamos de enviar un correo electr√≥nico con un enlace que activar√° su producto."
issue_or_digit = "O bien, tambi√©n puede introducir el c√≥digo de 6 d√≠gitos que le hemos enviado:"

# Context: this page - https://downloadhelper.net/
landing_text1 = "Descargue cualquier video de cualquier sitio web, ¬°funciona!"
landing_text2 = "M√°s de 1000 sitios web compatibles"
landing_text3 = "Con la confianza de 7 millones de usuarios"
landing_text4 = "4.5 estrellas en la tienda de extensiones"
landing_install_for_google = "Instalar para Chrome"
landing_install_for_mozilla = "Instalar para Firefox"
landing_install_for_microsoft = "Instalar para Edge"
landing_feature1_title = "Descarga HD a toda velocidad"
landing_feature1_description = "Descargue videos en alta definici√≥n a la m√°xima velocidad. Nos enorgullece afirmar que contamos con el motor de descarga m√°s r√°pido del mercado."
landing_feature2_title = "Archivar videos"
landing_feature2_description = "Archive sus videos favoritos y aseg√∫rese de que no se pierda nada."
landing_feature3_title = "Compatibilidad con transmisiones en directo"
landing_feature3_description = "Disfrute de reproducir transmisiones en directo sin tener que estar conectado en tiempo real."
landing_feature4_title = "Descarga de audio"
landing_feature4_description = "Extraiga el audio de los videos y convi√©rtalo a MP3 o podcasts para escucharlo f√°cilmente."

# Context: this is for a "Comprar una licencia" webpage.
premium_hero1 = "Pague una vez y √∫selo para siempre"
premium_hero2 = "Obtenga una licencia de por vida para Video DownloadHelper"
premium_hero3 = "Descargue todos los videos que quiera, sin l√≠mites."
