# ko.toml - v10.0.185.2
[addon]
appDesc = '''웹에서 동영상 다운로드.'''
restore_purchase_button = '''구매 복원'''
get_premium_button = '''프리미엄 얻기'''
back = '''뒤로'''
waiting_for_media = '''미디어 대기 중…'''
nomedia_title = '''찾으시는 미디어가 보이지 않나요?'''
nomedia_description = '''미디어 감지를 위해 동영상을 재생하세요 (광고가 있다면 건너뛰세요). 또는 미디어 누락을 신고하세요.'''
nomedia_reload_button = '''강제 감지'''
nomedia_reload_button_tooltip = '''페이지 강제 새로고침 (쿠키 삭제)'''
show_nomedia_button = '''동영상이 없나요?'''
show_nomedia_button_tooltip = '''동영상을 찾을 수 없으면 여기를 클릭하세요.'''
setting_button_tooltip = '''설정'''
history_button_tooltip = '''다운로드 기록 보기'''
show_all_history_button = '''모두 보기'''
complete_title = '''완료'''
hide_complete_button = '''숨기기'''
translate_button_tooltip = '''VDH 번역 돕기'''
open_source_tab_button_tooltip = '''소스 탭 열기'''
retry_download_button_tooltip = '''다운로드 재시도'''
delete_file_button_tooltip = '''파일 삭제'''
download_directory_button_tooltip = '''다운로드 폴더 표시'''
show_in_popup_button_tooltip = '''팝업으로 보기'''
show_in_sidebar_button_tooltip = '''사이드바로 보기'''
video_not_playing_button_tooltip = '''동영상이 재생되지 않나요?'''
play = '''재생'''
warn_drm_tooltip = '''DRM 감지됨'''
version_title = '''버전'''
account_title = '''계정'''
one_hundred_downloads_title = '''100개의 동영상을 다운로드하셨습니다!'''
leave_review_description = '''Video DownloadHelper를 즐겁게 사용하시길 바랍니다 :) 애드온 웹사이트에 좋은 리뷰를 남겨주시겠어요?'''
leave_review_button = '''리뷰 남기기'''
account_status = '''상태'''
account_status_premium = '''프리미엄 사용자'''
free_account = '''무료 플랜'''
copy_to_clipboard = '''정보를 클립보드에 복사'''
my_account_button = '''내 계정'''
download_title = '''다운로드'''
show_notification = '''다운로드 완료 시 알림 표시'''
max_parallel_downloads = '''최대 동시 다운로드 수'''
saveas_detected_warning = '''다운로드가 완료되면 브라우저에 '다른 이름으로 저장' 대화 상자가 나타나는 것을 감지했습니다. 브라우저 설정에서 이 옵션을 비활성화하는 것을 권장합니다.'''
change_saveas_setting = '''설정 변경'''
private_browsing_title = '''시크릿 브라우징'''
private_browsing_warning = '''Video DownloadHelper는 시크릿/비공개 창에서 활성화되어 있지 않습니다. 이 옵션을 수동으로 켜야 합니다 (필수는 아님).'''
private_browsing_notifications = '''시크릿 다운로드 알림 표시'''
private_browsing_button = '''시크릿 브라우징 설정 변경'''
prefer_original_audio = '''원본 오디오 선호'''
prefer_hls = '''HLS 선호'''
settings_history_title = '''기록'''
transient_history_description = '''완료된 다운로드 패널에 표시'''
history_limit = '''X일 후 다운로드 기록 삭제'''
appearance_title = '''모양'''
theme_title = '''테마'''
theme_light = '''밝게'''
theme_dark = '''어둡게'''
theme_system = '''시스템'''
popup_size_title = '''창 크기'''
popup_size_small = '''작게'''
popup_size_medium = '''중간'''
popup_size_big = '''크게'''
panel_position_title = '''패널 위치'''
use_popup = '''팝업으로 표시'''
use_sidebar = '''사이드바로 표시'''
behavior_title = '''동작'''
show_in_context_menu = '''페이지에서 마우스 오른쪽 클릭으로 명령에 액세스'''
restart_addon = '''애드온 다시 로드'''
reset_settings = '''설정 초기화'''
preview_mode_title = '''미디어 미리보기'''
preview_mode_none = '''비활성화됨'''
preview_mode_video = '''짧은 동영상 미리보기'''
preview_mode_image = '''이미지'''
history_title = '''다운로드 기록'''
history_warning = '''저희는 귀하의 다운로드 기록을 저장하지 않습니다. Video DownloadHelper가 귀하의 다운로드 기록을 기억하도록 하시겠습니까?'''
history_warning_2 = '''걱정하지 마세요, 모든 것은 귀하의 기기에만 저장됩니다. 저희는 귀하의 프라이버시를 소중히 여깁니다.'''
enable_history = '''기록 활성화'''
clear_history = '''기록 지우기'''
disable_history = '''내 기록을 기억하지 않기'''
no_downloads_yet = '''아직 항목이 없습니다.'''
download_failed = '''다운로드 실패'''
download_failed_description = '''죄송하게도 해당 미디어를 다운로드하는 데 실패했습니다. 저희는 가능한 많은 웹사이트를 지원하기 위해 노력하고 있으므로, 이 오류를 신고해 주시면 큰 도움이 됩니다 (익명입니다!).'''
download_interrupted = '''다운로드 중단됨'''
download_interrupted_description = '''파일을 다운로드하는 데 성공했지만, 네트워크 문제가 발생하여 파일이 예상보다 짧을 수 있습니다. 저희는 가능한 많은 웹사이트를 지원하기 위해 노력하고 있으므로, 이 문제를 신고해 주시면 큰 도움이 됩니다 (익명입니다!).'''
download_with_drm_failed_description = '''뭔가 제대로 작동하지 않았습니다. 그리고 이 동영상에는 DRM이 있는 것 같습니다. 저희는 DRM이 있는 동영상을 지원하지 않습니다.'''
no_youtube = '''YouTube 다운로드 허용 안 됨'''
no_youtube_description = ''' 아쉽게도 Chrome 웹 스토어는 YouTube 동영상 다운로드 확장 프로그램을 허용하지 않으므로, 이 기능을 Chrome 버전 확장 프로그램에 포함할 수 없었습니다.'''
premium_required = '''프리미엄 상태 필요'''
premium_yt_required_description = '''프리미엄 상태가 아니면 YouTube 다운로드는 이전 다운로드로부터 2시간 후에만 수행할 수 있습니다.'''
premium_hls_required_description = '''프리미엄 상태가 아니면 HLS 또는 MPD 다운로드는 이전 다운로드로부터 2시간 후에만 수행할 수 있습니다.'''
youtube_too_many_downloads = '''이런, YouTube가 차단된 것 같습니다.'''
youtube_too_many_downloads_description = '''YouTube는 때때로 요청할 수 있는 동영상 수를 제한합니다. 아쉽게도 저희가 할 수 있는 일은 없습니다. 나중에 다시 시도해 보세요.'''
stop = '''중지'''
cancel = '''취소'''
copy_url = '''URL 복사'''
always_copy_url = '''항상 URL 복사'''
download_button = '''다운로드'''
download_as_button_and_menu = '''다른 이름으로 다운로드...'''
rename_short = '''이름 변경'''
always_download_as_menu = '''항상 다른 이름으로 다운로드…'''
download_audio_button = '''오디오'''
download_audio_and_video_menu = '''오디오 및 동영상 다운로드'''
download_audio_only_menu = '''오디오만 다운로드'''
audio_only_for_this_website = '''이 웹사이트에서는 항상 오디오만'''
details = '''세부 정보'''
report = '''신고'''
reporting = '''신고 중...'''
reported_thankyou = '''감사합니다!'''
not_playing_title = '''동영상이 재생되지 않나요?'''
not_playing_broken_title = '''오디오 또는 동영상이 깨졌나요?'''
not_playing_broken_description = '''실패한 미디어를 신고하세요. 왜 실패했는지 알아내기 위해 최선을 다하겠습니다 (동영상 URL을 익명으로 보냅니다 - 추적하지 않습니다!)'''
not_playing_broken_solution_title = '''최신 동영상 플레이어를 사용해 보세요'''
not_playing_broken_solution_windows_1 = '''VLC를 권장합니다:'''
not_playing_broken_solution_mac_1 = '''IINA를 권장합니다:'''
not_playing_broken_solution_2 = '''최신이고 안전하며 오픈 소스입니다.'''
not_playing_default_player = '''동영상 플레이어가 시스템 기본 동영상 플레이어로 설정되어 있는지 확인하세요.'''
not_playing_default_player_solution_windows = '''Windows의 "제어판"에서 "기본 프로그램"을 클릭하고 플레이어의 기본 프로그램을 변경하세요.'''
not_playing_default_player_solution_mac = '''다운로드 디렉토리를 열고 동영상 파일을 마우스 오른쪽 버튼으로 클릭합니다. '정보 가져오기'를 클릭합니다. '연결 프로그램' 섹션에서 IINA를 선택합니다. '모두 변경' 버튼을 클릭합니다.'''

[web]
back = '''뒤로'''
header_help = '''도움말'''
header_community = '''커뮤니티'''
activate_title = '''활성화'''
activate_pending = '''대기 중...'''
activate_success = '''성공'''
activate_error = '''오류'''
activate_no_addon_found = ''' 애드온을 찾을 수 없습니다. 애드온이 설치되어 있나요?'''
activate_no_method_found = '''방법을 찾을 수 없습니다.'''
activate_help_me = '''도와주세요.'''
issue_title = '''구매복원'''
issue_submit = '''제출'''
issue_thank_you = '''감사합니다.'''
issue_enter_email = '''구매를 복원하려면 라이선스를 구매할 때 사용한 이메일 주소를 입력하세요:'''
issue_email_sent = '''제품을 활성화할 수 있는 링크가 포함된 이메일을 방금 보내드렸습니다.'''
issue_or_digit = '''또는, 저희가 보내드린 6자리 코드를 입력할 수도 있습니다:'''
issue_just_digit = '''저희가 보내드린 6자리 코드를 입력하세요:'''
issue_i_have_a_code = '''(이미 코드가 있다면 여기를 클릭하세요)'''
issue_i_have_a_key = '''(라이선스 키가 있다면 여기를 클릭하세요)'''
issue_key = '''Video DownloadHelper 라이선스 키를 입력하세요:'''
landing_text1 = '''어떤 웹사이트에서든 동영상을 다운로드하세요, 그냥 작동합니다!'''
landing_text2 = '''1000개 이상의 웹사이트 지원'''
landing_text3 = '''7백만 사용자의 신뢰'''
landing_text4 = '''확장 프로그램 스토어에서 4.5점 평점'''
landing_install_for_google = '''Chrome용 설치'''
landing_install_for_mozilla = '''Firefox용 설치'''
landing_install_for_microsoft = '''Edge용 설치'''
landing_feature1_title = '''고속 HD 다운로드'''
landing_feature1_description = '''고화질 동영상을 최고 속도로 다운로드하세요. 저희는 가장 빠른 다운로드 엔진을 보유하고 있다고 자랑스럽게 말씀드립니다.'''
landing_feature2_title = '''동영상 보관'''
landing_feature2_description = '''좋아하는 동영상을 보관하여 아무것도 놓치지 않도록 합니다.'''
landing_feature3_title = ''' 라이브 스트림 지원'''
landing_feature3_description = '''라이브 스트림을 오프라인으로 시청하여 실시간 제약에서 벗어나세요.'''
landing_feature4_title = '''오디오 다운로드'''
landing_feature4_description = '''동영상에서 오디오를 추출하여 MP3 또는 팟캐스트로 변환하여 쉽게 들을 수 있습니다.'''
premium_hero1 = '''한 번 결제하고 영원히 사용하세요'''
premium_hero2 = '''Video DownloadHelper 평생 라이선스를 받으세요'''
premium_hero3 = '''원하는 만큼 모든 동영상을 제한 없이 다운로드하세요.'''
welcome_text = '''이제 어떤 동영상도 놓치지 않을 거예요!'''
welcome_pin_message = '''애드온 아이콘을 도구 모음에 고정하세요:'''
