# pt-BR.toml - v10.1.37.2
[addon]
appDesc = '''Baixar vídeos da Web.'''
restore_purchase_button = '''Restaurar compra'''
get_premium_button = '''Obter premium'''
back = '''Voltar'''
rm_notifications_all = '''Descartar todas as notificações'''
waiting_for_media = '''Esperando pela mídia…'''
nomedia_title = '''Não consegue ver a mídia que está procurando?'''
nomedia_description = '''Inicie o vídeo (e pule os anúncios, se houver) para ajudar a detectar a mídia. Ou relate a mídia ausente. '''
nomedia_reload_button = '''Forçar detecção'''
nomedia_reload_button_tooltip = '''Forçar o recarregamento da página (limpar cookies)'''
show_nomedia_button = '''Sem vídeo?'''
show_nomedia_button_tooltip = '''Clique aqui se não conseguir encontrar seu vídeo'''
setting_button_tooltip = '''Configurações'''
history_button_tooltip = '''Mostrar histórico de downloads'''
show_all_history_button = '''mostrar tudo'''
complete_title = '''Concluído'''
hide_complete_button = '''esconder'''
translate_button_tooltip = '''Ajude a traduzir o VDH'''
help_button_tooltip = '''Ajuda'''
open_source_tab_button_tooltip = '''Abrir aba de origem'''
retry_download_button_tooltip = '''Baixar novamente'''
delete_file_button_tooltip = '''Excluir arquivo'''
download_directory_button_tooltip = '''Mostrar pasta de download'''
clear_downloaded_tooltip = '''Limpar downloads concluídos'''
show_in_popup_button_tooltip = '''Mostrar em pop-up'''
show_in_sidebar_button_tooltip = '''Mostrar na barra lateral'''
video_not_playing_button_tooltip = '''Sem vídeo?'''
play = '''Reproduzir'''
warn_drm_tooltip = '''DRM detectado'''
version_title = '''Versão'''
account_title = '''Conta'''
one_hundred_downloads_title = '''Você baixou 100 vídeos!'''
leave_review_description = '''Esperamos que esteja gostando do Vídeo DownloadHelper :) Você se importaria de escrever uma boa crítica no site da extensão?'''
leave_review_button = '''Deixe um comentário'''
account_status = '''Status'''
account_status_premium = '''Premium ($1)'''
free_account = '''Plano gratuito'''
copy_to_clipboard = '''Copiar informações para a área de transferência'''
my_account_button = '''Minha conta'''
download_title = '''Downloads'''
show_notification = '''Mostrar notificação quando o download for concluído'''
max_parallel_downloads = '''Máximo de downloads simultâneos'''
saveas_detected_warning = ''' Detectamos que seu navegador mostra um diálogo "Salvar como" quando o download é concluído. Recomendamos desativar essa opção nas configurações do seu navegador'''
change_saveas_setting = '''Alterar configuração'''
download_directory_title = '''Diretório de downloads'''
download_directory_description = '''Os vídeos são baixados no diretório de downloads padrão do navegador. Você também pode especificar um subdiretório. Diretórios de download específicos para cada site podem ser definidos com a ferramenta de nomeação inteligente (smartnaming)'''
change_browser_download_directory = '''Alterar o diretório de download do navegador'''
bad_download_subdirectory_warning = '''O subdiretório especificado não é válido.'''
download_subdirectory = '''Subdiretório de downloads'''
private_browsing_title = '''Navegação privativa'''
private_browsing_warning = '''O Video DownloadHelper não está ativado em janelas privativas/anônimas. Você precisa ativar essa opção manualmente (isso não é obrigatório).'''
private_browsing_notifications = '''Mostrar notificação para downloads privativos'''
private_browsing_button = '''Alterar a configuração de navegação privativa'''
throttle_youtube = '''Limitar largura de banda do YouTube (downloads mais lentos, mas menos chance de ser bloqueado)'''
prefer_original_audio = '''Preferir áudio original'''
prefer_hls = '''Preferir HLS'''
settings_history_title = '''Histórico'''
transient_history_description = '''Mostrar downloads completos no painel'''
history_limit = '''Esquecer o histórico de downloads após X dias'''
appearance_title = '''Aparência'''
theme_title = '''Tema'''
theme_light = '''claro'''
theme_dark = '''escuro'''
theme_system = '''sistema'''
popup_size_title = '''Tamanho da janela'''
popup_size_small = '''Pequeno'''
popup_size_medium = '''Médio'''
popup_size_big = '''Grande'''
panel_position_title = '''Posição do painel'''
use_popup = '''Mostrar em pop-up'''
use_sidebar = '''Mostrar na barra lateral'''
behavior_title = '''Comportamento'''
controls_title = '''Controles'''
show_in_context_menu = '''Acessar comandos pelo botão direito na página'''
restart_addon = '''Recarregar extensão'''
reset_settings = '''Redefinir configurações'''
prefered_quality = '''Qualidade de vídeo preferida'''
prefered_quality_highest = '''Mais alta (download lento, alta resolução)'''
prefered_quality_1080p = '''1080p (valor padrão)'''
prefered_quality_720p = '''720p (download rápido, baixa resolução)'''
prefer_mkv = '''Baixar como MKV quando possível'''
preview_mode_title = '''Prévia de mídia'''
preview_mode_none = '''Desativado'''
preview_mode_video = '''Prévia curta do vídeo'''
preview_mode_image = '''Imagem'''
history_title = '''Histórico de downloads'''
history_warning = '''Não registramos seu histórico de downloads. Deseja que o Video DownloadHelper lembre do seu histórico de downloads?'''
history_warning_2 = '''Não se preocupe, tudo fica na sua máquina. Valorizamos sua privacidade.'''
enable_history = '''Lembrar histórico'''
clear_history = '''Limpar histórico'''
disable_history = '''Não lembrar meu histórico'''
no_downloads_yet = '''Nenhuma entrada'''
download_failed = '''Download falhou'''
download_failed_description = '''Infelizmente, falhamos no download dessa mídia específica. Tentamos oferecer suporte ao maior número possível de sites, então ajudaria muito se você pudesse relatar esse erro!'''
download_interrupted = '''Download interrompido'''
download_interrupted_description = '''Conseguimos baixar seu arquivo, mas houve um problema de rede, então o arquivo pode estar menor do que o esperado. Tentamos oferecer suporte ao maior número possível de sites, então ajudaria muito se você pudesse relatar esse problema (é anônimo!).'''
download_with_drm_failed_description = '''Algo não deu certo. E achamos que este vídeo possui DRM. Não oferecemos suporte a vídeos com DRM.'''
no_youtube = '''Não é permitido baixar do YouTube'''
no_youtube_description = '''Infelizmente, a Chrome Web Store não permite extensões para baixar vídeos do YouTube, por isso não conseguimos incluir este recurso na versão da extensão para o Chrome.'''
no_youtube_description_2 = '''Use o Firefox ou o Microsoft Edge'''
premium_required = '''É necessário status Premium'''
premium_yt_required_description = '''Sem o status Premium, o download de um vídeo do YouTube só pode ser realizado 2 horas após o anterior.'''
premium_hls_required_description = '''Sem o status Premium, o download de HLS ou MPD só pode ser realizado 2 horas após o anterior.'''
premium_all_required_description = '''Sem o status Premium, um download só pode ser realizado 2 horas após o anterior.'''
youtube_too_many_downloads = '''Ops, parece que o YouTube está bloqueado'''
youtube_too_many_downloads_description = '''O YouTube às vezes limita a quantidade de vídeos que podem ser solicitados. Infelizmente, não há nada que possamos fazer a respeito. Tente novamente mais tarde.'''
stop = '''Parar'''
cancel = '''Cancelar'''
copy_url = '''Copiar URL'''
always_copy_url = '''Sempre copiar URL'''
download_button = '''Baixar'''
download_as_button_and_menu = '''Baixar como…'''
rename_short = '''Renomear'''
always_download_as_menu = '''Sempre baixar como…'''
download_audio_button = '''Áudio'''
download_audio_and_video_menu = '''Baixar áudio e vídeo'''
download_audio_only_menu = '''Baixar áudio'''
audio_only_for_this_website = '''Sempre apenas áudio para este site'''
details = '''Detalhes'''
report = '''Relatar'''
reporting = '''Relatando…'''
reported_thankyou = '''Agradecemos!'''
not_playing_title = '''Problemas com a reprodução do vídeo?'''
not_playing_broken_title = '''Áudio ou vídeo quebrado?'''
not_playing_broken_description = '''Relatar falha na mídia. Faremos o nosso melhor para descobrir por que ela falhou (enviamos a URL do vídeo anonimamente – não rastreamos você!)'''
not_playing_broken_solution_title = '''Experimente um reprodutor de vídeo moderno'''
not_playing_broken_solution_windows_1 = '''Recomendamos o VLC:'''
not_playing_broken_solution_mac_1 = '''Recomendamos o IINA:'''
not_playing_broken_solution_2 = '''é moderno, seguro e de código aberto.'''
not_playing_default_player = '''Certifique-se de que seu reprodutor de vídeo esteja definido como o reprodutor de vídeo padrão do sistema'''
not_playing_default_player_solution_windows = '''No 'Painel de Controle' do Windows, clique em 'Programas Padrão' e altere os programas padrão para o seu reprodutor.'''
not_playing_default_player_solution_mac = '''Abra a pasta de downloads e clique com o botão direito no arquivo de vídeo. Clique em 'Obter informações'. Na seção 'Abrir com', selecione IINA. Clique no botão 'Alterar tudo'.'''

[web]
back = '''Voltar'''
header_help = '''Ajuda'''
header_ask_question = '''Faça-nos uma pergunta'''
activate_title = '''Ativação'''
activate_pending = '''Pendente…'''
activate_success = '''Sucesso'''
activate_error = '''Erro'''
activate_no_addon_found = '''Nenhuma extensão encontrada. A extensão está instalada?'''
activate_no_method_found = '''Nenhum método encontrado.'''
activate_help_me = '''Ajude-me.'''
issue_title = '''Restaurando compra'''
issue_submit = '''Enviar'''
issue_thank_you = '''Agradecemos'''
issue_enter_email = '''Para restaurar sua compra, insira o endereço de e-mail que usou para comprar sua licença:'''
issue_email_sent = '''Acabamos de enviar um e-mail com um link que ativará seu produto.'''
issue_or_digit = '''Ou insira o código de 6 dígitos que enviamos:'''
issue_just_digit = '''Digite o código de 6 dígitos que lhe enviamos:'''
issue_i_have_a_code = '''(Clique aqui se já tiver um código)'''
issue_i_have_a_key = '''(Clique aqui se você já possui uma chave de licença)'''
issue_key = '''Digite sua chave de licença do Video DownloadHelper:'''
landing_text1 = '''Baixe qualquer vídeo de qualquer site, simplesmente funciona!'''
landing_text2 = '''Mais de 1000 sites suportados'''
landing_text3 = '''Utilizado por 7 milhões de usuários'''
landing_text4 = '''4,5 estrelas na loja de extensões'''
landing_install_for_google = '''Instalar para o Chrome'''
landing_install_for_mozilla = '''Instalar para o Firefox'''
landing_install_for_microsoft = '''Instalar para o Edge'''
landing_feature1_title = '''Baixar em HD na velocidade máxima'''
landing_feature1_description = '''Baixe vídeos em alta definição, na velocidade máxima. Temos orgulho de afirmar que possuímos o motor de download mais rápido do mercado.'''
landing_feature2_title = '''Arquivar vídeos'''
landing_feature2_description = '''Arquive seus vídeos favoritos, garantindo que nada seja deixado para trás.'''
landing_feature3_title = '''Suporte a transmissões ao vivo'''
landing_feature3_description = '''Assista às transmissões ao vivo offline, libertando você das restrições do tempo real.'''
landing_feature4_title = '''Baixar áudio'''
landing_feature4_description = '''Extraia o áudio de vídeos, convertendo-os em MP3s ou podcasts para ouvir com facilidade.'''
premium_hero1 = '''Pague uma vez, use para sempre'''
premium_hero2 = '''Adquira a Licença Vitalícia do Video DownloadHelper'''
premium_hero3 = '''Baixe quantos vídeos quiser, sem limites.'''
welcome_text = '''Agora você não perde mais nenhum vídeo!'''
welcome_pin_message = '''Fixe o ícone da extensão na sua barra de ferramentas:'''
