# Turkish
# tr.toml - v10.0.183.2
[addon]
appDesc = "Web'den Videolar İndirin."
restore_purchase_button = "Satın alımı geri yükle"
get_premium_button = "Premium al"
back = "Geri"
waiting_for_media = "Medya için bekleniyor..."
nomedia_title = "Aradığın medyayı göremiyor musun?"
nomedia_description = "Medya tespitine yardımcı olmak için videoyu başlat (varsa reklamları atla). Veya kayıp medyayı raporla."
nomedia_reload_button = "Tespite zorla"
nomedia_reload_button_tooltip = "Zorla sayfayı yenile (çerezleri temizler)"
show_nomedia_button = "Video yok mu?"
show_nomedia_button_tooltip = "Eğer videonu bulamıyorsan buraya tıkla"
setting_button_tooltip = "Ayarlar"
history_button_tooltip = "İndirme Geçmişini Göster"
show_all_history_button = "tümünü göster"
complete_title = "Tamamlanmış"
hide_complete_button = "gizle"
translate_button_tooltip = "VDH çevirisine yardımcı ol"
open_source_tab_button_tooltip = "Kaynak sekmesini aç"
retry_download_button_tooltip = "İndirmeyi tekrar dene"
delete_file_button_tooltip = "Dosyayı sil"
download_directory_button_tooltip = "İndirme klasörünü göster"
show_in_popup_button_tooltip = "Açılır pencerede göster"
show_in_sidebar_button_tooltip = "Kenar çubuğunda göster"
video_not_playing_button_tooltip = "Video oynamıyor mu?"
play = "Oynat"
warn_drm_tooltip = "DRM algılandı"
version_title = "Sürüm"
account_title = "Hesap"
one_hundred_downloads_title = "100 video indirdin!"
leave_review_description = "Video DownloadHelper'ı beğendiğini umuyoruz :) Eklenti web sitesine hoş bir inceleme yazman mümkün mü?"
leave_review_button = "İnceleme yaz"
account_status = "Durum"
account_status_premium = "Premium ($1)"
free_account = "Ücretsiz plan"
copy_to_clipboard = "Bilgiyi panoya kopyala"
my_account_button = "Hesabım"
download_title = "İndirmeler"
show_notification = "İndirme tamamlanınca bildirim göster"
max_parallel_downloads = "Maks eş zamanlı indirme"
change_download_directory = "İndirme dizinini değiştir"
saveas_detected_warning = "İndirme işlemi tamamlandıktan sonra tarayıcınızın 'Farklı Kaydet' iletişim kutusunu gösterdiğini tespit ettik. Bu seçeneği tarayıcı ayarlarınızdan devre dışı bırakmanızı öneririz."
change_saveas_setting = "Ayarı değiştir"
private_browsing_title = "Gizli gezinme"
private_browsing_warning = "Video DownloadHelper, Özel/Gizli pencerelerde etkin değil. Bu seçeneği manuel olarak açmanız gerekiyor (zorunlu değil)."
private_browsing_notifications = "Gizli indirmeler için bildirim göster"
private_browsing_button = "Gizli gezinme ayarını değiştir"
prefer_original_audio = "Orijinal sesi tercih et"
prefer_hls = "HLS tercih et"
settings_history_title = "Geçmiş"
transient_history_description = "Panelde tamamlanmış indirmeleri göster"
history_limit = "X gün sonra indirme geçmişini unut"
appearance_title = "Görünüm"
theme_title = "Tema"
theme_light = "aydınlık"
theme_dark = "karanlık"
theme_system = "sistem"
popup_size_title = "Pencere boyutu"
popup_size_small = "Küçük"
popup_size_medium = "Orta"
popup_size_big = "Büyük"
panel_position_title = "Panel pozisyonu"
use_popup = "Açılır pencerede göster"
use_sidebar = "Kenar çubuğunda göster"
behavior_title = "Davranış"
show_in_context_menu = "Sayfada sağ tık menüsünden komutlara eriş"
restart_addon = "Eklentiyi yeniden yükle"
reset_settings = "Ayarları sıfırla"
preview_mode_title = "Medya önizlemesi"
preview_mode_none = "Devredışı"
preview_mode_video = "Kısa video önizlemesi"
preview_mode_image = "Resim"
history_title = "İndirme Geçmişi"
history_warning = "İndirme geçmişinizi kaydetmiyoruz. Video DownloadHelper'ın indirme geçmişini hatırlamasını ister misin?"
history_warning_2 = "Endişelenmeyin, her şey bilgisayarınızda kalır. Gizliliğinize değer veriyoruz."
enable_history = "Geçmişi Etkinleştir"
clear_history = "Geçmişi Temizle"
disable_history = "Geçmişimi hatırlama"
no_downloads_yet = "Henüz giriş yok."
download_failed = "İndirme başarısız"
download_failed_description = "Maalesef söz konusu medyayı indirmeyi başaramadık. Mümkün olduğunca çok web sitesini desteklemeye çalışıyoruz, bu nedenle bu hatayı bildirirseniz bize çok yardımcı olursunuz (anonimdir!)."
download_interrupted = "İndirme kesintiye uğradı"
download_interrupted_description = "Dosyanızı indirmeyi başardık, ancak bir ağ sorunu oluştu, bu nedenle dosya beklenenden daha kısa olabilir. Mümkün olduğunca çok web sitesini desteklemeye çalışıyoruz, bu nedenle bu hatayı bildirirseniz bize çok yardımcı olursunuz (anonimdir!)."
download_with_drm_failed_description = "Bir sorun oluştu. Bu videonun DRM korumasına sahip olduğunu düşünüyoruz. DRM korumasına sahip videoları desteklemiyoruz."
no_youtube = "Youtube'dan indirmeye izin verilmiyor"
no_youtube_description = "Ne yazık ki Chrome Web Mağazası YouTube videolarını indirmek için eklentilere izin vermiyor, bu nedenle eklentinin Chrome sürümüne bu özelliği ekleyemedik."
premium_required = "Premium statü gerekli"
premium_yt_required_description = "Premium statüsü olmadan YouTube indirme işlemi bir öncekinden en fazla 2 saat sonra gerçekleştirilebilir."
premium_required_description = "Premium statüsü olmadan HLS veya MPD indirme işlemi bir öncekinden en fazla 2 saat sonra gerçekleştirilebilir."
youtube_too_many_downloads = "Eyvah, YouTube engellenmiş görünüyor"
youtube_too_many_downloads_description = "YouTube bazen istenebilecek video sayısını sınırlayabilir. Maalesef yapabileceğimiz bir şey yok. Daha sonra tekrar deneyin."
stop = "Dur"
cancel = "İptal"
copy_url = "URL'yi Kopyala"
always_copy_url = "Her zaman URL'yi kopyala"
download_button = "İndir"
download_as_button_and_menu = "Farklı İndir..."
rename_short = "Yeniden Adlandır"
always_download_as_menu = "Her Zaman Farklı İndir..."
download_audio_button = "Ses"
download_audio_and_video_menu = "Ses & Video İndir"
download_audio_only_menu = "Ses İndir"
audio_only_for_this_website = "Bu website için her zaman sadece ses"
details = "Detaylar"
more_settings = "Daha fazla ayar"
report = "Bildir"
reporting = "Bildiriliyor..."
reported_thankyou = "Teşekkürler!"
not_playing_title = "Video oynamıyor mu?"
not_playing_broken_title = "Bozuk ses veya video?"
not_playing_broken_description = "Başarısız olan medyayı bildirin. Neden başarısız olduğunu anlamak için elimizden geleni yapacağız (video URL'sini anonim olarak gönderiyoruz - sizi takip etmiyoruz!)"
not_playing_broken_solution_title = "Modern bir video oynatıcı dene"
not_playing_broken_solution_windows_1 = "Biz VLC öneriyoruz:"
not_playing_broken_solution_mac_1 = "Biz IINA öneriyoruz:"
not_playing_broken_solution_2 = "Modern, güvenli ve Açık Kaynaklıdır."
not_playing_default_player = "Video oynatıcınızın sisteminizin varsayılan video oynatıcısı olarak ayarlandığından emin olun"
not_playing_default_player_solution_windows = "Windows'un 'Kontrol Paneli' nden 'Varsayılan Programlar'a tıklayıp oynatıcınızın varsayılan programlarını değiştirebilirsiniz."
not_playing_default_player_solution_mac = "İndirilenler klasörünü açın ve video dosyasına sağ tıklayın. 'Bilgi Al' seçeneğine tıklayın. 'Birlikte Aç' bölümünden IINA'yı seçin. Sonra da 'Tümünü Değiştir' butonuna basın."

[web]
back = "Geri"
header_help = "Yardım"
header_community = "Topluluk"
activate_title = "Etkinleştirme"
activate_pending = "Bekliyor..."
activate_success = "Başarılı"
activate_error = "Hata"
activate_no_addon_found = "Hiçbir eklenti bulunamadı. Eklenti kurulu mu?"
activate_no_method_found = "Hiçbir metod bulunamadı."
activate_help_me = "Bana yardım et."
issue_title = "Satın alımlar geri yükleniyor"
issue_submit = "Gönder"
issue_thank_you = "Teşekkürler"
issue_enter_email = "Satın alımınızı geri yüklemek için lisansınızı alırken kullandığınız e-posta adresini girin:"
issue_email_sent = "Size ürününüzü etkinleştirecek bağlantıyı içeren bir e-posta gönderdik."
issue_or_digit = "Veya size gönderdiğimiz 6 haneli kodu girebilirsiniz:"
issue_just_digit = "Size gönderdiğimiz 6 haneli kodu girin:"
issue_i_have_a_code = "(Eğer koda zaten sahipseniz buraya tıklayın)"
issue_i_have_a_key = "(Eğer lisansınız varsa buraya tıklayın)"
issue_key = "Video DownloadHelper lisans anahtarınızı girin:"
landing_text1 = "İstediğiniz videoyu istediğiniz websitesinden indirin, işe yarıyor!"
landing_text2 = "1000+ website destekleniyor"
landing_text3 = "7 milyon kullanıcı tarafından güveniliyor"
landing_text4 = "Eklenti mağazasında 4.5 yıldız"
landing_install_for_google = "Chrome için İndir"
landing_install_for_mozilla = "Firefox için İndir"
landing_install_for_microsoft = "Edge için İndir"
landing_feature1_title = "Son hız HD İndirme"
landing_feature1_description = "Videoları yüksek çözünürlükte ve maksimum hızda indirin. Piyasadaki en hızlı indirme motoruna sahip olduğumuzu iddia etmekten gurur duyuyoruz."
landing_feature2_title = "Videoları arşivle"
landing_feature2_description = "En sevdiğiniz videoları arşivleyin, hiçbir şeyin geride kalmadığından emin olun."
landing_feature3_title = "Canlı Akış Desteği"
landing_feature3_description = "Canlı yayınları çevrimdışı izlemenin keyfini çıkarın, gerçek zamanlı kısıtlamalardan kurtulun."
landing_feature4_title = "Ses İndirme"
landing_feature4_description = "Videolardan ses dosyalarını çıkarın ve bunları kolay dinleme için MP3'lere veya podcast'lere dönüştürün."
premium_hero1 = "Bir kere öde, ömür boyu kullan"
premium_hero2 = "Video DownloadHelper için Ömür Boyu Lisans Al"
premium_hero3 = "İstediğiniz kadar videoyu indirin, hiçbir sınırlama yok."
welcome_text = "Artık hiçbir videoyu kaçırmayacaksınız!"
welcome_pin_message = "Eklenti simgesini araç çubuğunuza sabitleyin:"
