# Chinese - Taiwan

[addon]

# Video DownloadHelper description. 132 characters max.
appDesc = "å¾ç¶²è·¯ä¸Šä¸‹è¼‰å½±ç‰‡ã€‚"

# Global strings
restore_purchase_button = "æ¢å¾©è³¼è²·"
get_premium_button = "å–å¾—ä»˜è²»ç‰ˆ"
back = "è¿”å›" # Go back button - in Settings panel for example

# Strings for the main panel
waiting_for_media = "æ­£åœ¨ç­‰å¾…åª’é«”â€¦"
nomedia_title = "çœ‹ä¸åˆ°æ‚¨è¦å°‹æ‰¾çš„åª’é«”ï¼Ÿ"
nomedia_description = "è«‹é–‹å§‹å½±ç‰‡ (å¦‚æœæœ‰å»£å‘Šï¼Œè«‹ç•¥é)ï¼Œä»¥å”åŠ©åµæ¸¬åª’é«”ã€‚æˆ–å›å ±åª’é«”éºå¤±ã€‚"
nomedia_reload_button = "å¼·åˆ¶åµæ¸¬"
nomedia_reload_button_tooltip = "å¼·åˆ¶é é¢é‡æ–°è¼‰å…¥ (æ¸…é™¤ Cookie)"
show_nomedia_button = "æ²’æœ‰å½±ç‰‡ï¼Ÿ"
show_nomedia_button_tooltip = "å¦‚æœæ‰¾ä¸åˆ°å½±ç‰‡ï¼Œè«‹æŒ‰ä¸€ä¸‹æ­¤è™•"
setting_button_tooltip = "è¨­å®š"
history_button_tooltip = "é¡¯ç¤ºä¸‹è¼‰ç´€éŒ„"
translate_button_tooltip = "å”åŠ©ç¿»è­¯ VDH"

# Downloaded media box
open_source_tab_button_tooltip = "é–‹å•Ÿä¾†æºåˆ†é "
retry_download_button_tooltip = "é‡è©¦ä¸‹è¼‰"
delete_file_button_tooltip = "åˆªé™¤æª”æ¡ˆ"
download_directory_button_tooltip = "é¡¯ç¤ºä¸‹è¼‰ç›®éŒ„"
show_in_popup_button_tooltip = "åœ¨å¿«é¡¯è¦–çª—ä¸­é¡¯ç¤º"
show_in_sidebar_button_tooltip = "åœ¨å´é‚Šæ¬„ä¸­é¡¯ç¤º"
video_not_playing_button_tooltip = "ç„¡æ³•æ’­æ”¾å½±ç‰‡ï¼Ÿ"
play = "æ’­æ”¾"
warn_drm_tooltip = "åµæ¸¬åˆ° DRM"

# Strings for the settings panel.
version_title = "ç‰ˆæœ¬"
account_title = "å¸³æˆ¶"
leave_review_description = "å—¨ ğŸ¤š Video DownloadHelper å¯ä¾›å…è²»ä½¿ç”¨ã€‚æ‚¨é¡˜æ„ç•™ä¸‹å¥½è©•å—ï¼Ÿé€™å°æˆ‘æœ‰å¾ˆå¤§çš„å¹«åŠ© ğŸ˜Šã€‚"
leave_review_button = "ç•™ä¸‹è©•è«–"
account_status= "ç‹€æ…‹"
account_status_premium = "ä»˜è²»ç‰ˆ ($1)" # $1 is the store (Mozilla, Google, Microsoft, All)
free_account = "å…è²»æ–¹æ¡ˆ"
copy_to_clipboard = "è¤‡è£½åˆ°å‰ªè²¼ç°¿"
my_account_button = "æˆ‘çš„å¸³æˆ¶"
download_title = "ä¸‹è¼‰"
show_notification = "ä¸‹è¼‰å®Œæˆå¾Œï¼Œé¡¯ç¤ºé€šçŸ¥"
max_parallel_downloads = "åŒæ™‚ä¸‹è¼‰ä¸Šé™"
change_download_directory = "è®Šæ›´ä¸‹è¼‰ç›®éŒ„"

private_browsing_title = "ç§å¯†ç€è¦½"
private_browsing_warning = "åœ¨ç§å¯†ç€è¦½æ¨¡å¼ä¸‹ï¼Œç„¡æ³•ä½¿ç”¨ Video DownloadHelperã€‚"
private_browsing_notifications = "é¡¯ç¤ºç§å¯†ä¸‹è¼‰é€šçŸ¥"
private_browsing_button = "è®Šæ›´ç§å¯†ç€è¦½è¨­å®š"
prefer_original_audio = "åå¥½åŸå§‹éŸ³è¨Š" # Firefox only
prefer_hls = "åå¥½ HLS" # Firefox only
settings_history_title = "ç´€éŒ„"
history_limit = "å¿˜è¨˜ä¸‹è¼‰ä¹‹å‰çš„å¤©æ•¸"
appearance_title = "å¤–è§€"
theme_title = "ä¸»é¡Œ"
theme_light = "æ·ºè‰²ä¸»é¡Œ"
theme_dark = "æ·±è‰²ä¸»é¡Œ"
theme_system = "ç³»çµ±ä¸»é¡Œ"
popup_size_title = "è¦–çª—å¤§å°"
popup_size_small = "å°"
popup_size_medium = "ä¸­"
popup_size_big = "å¤§"
panel_position_title = "é¢æ¿ä½ç½®"
use_popup = "ä½¿ç”¨å¿«é¡¯è¦–çª—"
use_sidebar = "ä½¿ç”¨å´é‚Šæ¬„"
behavior_title = "è¡Œç‚º"
show_in_context_menu = "åœ¨é é¢æƒ…å¢ƒé¸å–®ä¸­ï¼Œé¡¯ç¤ºä¸‹è¼‰é¸å–®"
restart_addon = "é‡æ–°å•Ÿå‹•é™„åŠ å…ƒä»¶"
reset_settings = "é‡è¨­è¨­å®š"
prefer_highest_quality = "é è¨­é¸æ“‡æœ€é«˜å“è³ªï¼Œè€Œä¸æ˜¯ 1080p (ä¸‹è¼‰é€Ÿåº¦è¼ƒæ…¢ï¼Œå“è³ªè¼ƒé«˜)ã€‚"

# String for history page
history_title = "ä¸‹è¼‰ç´€éŒ„"
history_warning = "æˆ‘å€‘ä¸æœƒè¨˜éŒ„æ‚¨çš„ä¸‹è¼‰ç´€éŒ„ã€‚æ˜¯å¦è¦ Video DownloadHelper è¨˜ä½æ‚¨çš„ä¸‹è¼‰ç´€éŒ„ï¼Ÿ"
history_warning_2 = "åˆ¥æ“”å¿ƒï¼Œä¸€åˆ‡éƒ½æœƒä¿ç•™åœ¨æ‚¨çš„é›»è…¦ä¸Šã€‚æˆ‘å€‘é‡è¦–æ‚¨çš„éš±ç§ã€‚"
enable_history = "å•Ÿç”¨ç´€éŒ„"
clear_history = "æ¸…é™¤ç´€éŒ„"
disable_history = "åœç”¨ç´€éŒ„"
no_downloads_yet = "å°šç„¡ä»»ä½•ä¸‹è¼‰ã€‚"

# Various notifications
download_failed = "ä¸‹è¼‰å¤±æ•—"
download_failed_description = "ç™¼ç”Ÿå•é¡Œã€‚è«‹å›å ±éŒ¯èª¤ï¼Œæˆ‘å€‘å°‡ç›¡åŠ›æ‰¾å‡ºå¤±æ•—çš„åŸå›  (æˆ‘å€‘ä»¥åŒ¿åæ–¹å¼å‚³é€å½±ç‰‡ URLï¼ä¸æœƒè¿½è¹¤æ‚¨ï¼)ã€‚"
download_with_drm_failed_description = "ç™¼ç”Ÿå•é¡Œã€‚æˆ‘å€‘èªç‚ºé€™æ”¯å½±ç‰‡æœ‰ DRMã€‚æˆ‘å€‘ä¸æ”¯æ´æœ‰ DRM çš„å½±ç‰‡ã€‚"
no_youtube = "ä¸å…è¨±å¾ YouTube ä¸‹è¼‰"
no_youtube_description = "å¾ˆæŠ±æ­‰ï¼ŒChrome ç·šä¸Šæ‡‰ç”¨ç¨‹å¼å•†åº—ï¼Œä¸å…è¨±æ“´å……åŠŸèƒ½ä¸‹è¼‰ YouTube å½±ç‰‡ã€‚å…¶ä»–ç€è¦½å™¨ (ä¾‹å¦‚ Firefox) æ²’æœ‰æ­¤é™åˆ¶ã€‚"
premium_required = "éœ€è¦ä»˜è²»ç‰ˆ"
premium_yt_required_description = "å¦‚æœæ˜¯å…è²»ç‰ˆä½¿ç”¨è€…ï¼Œå¿…é ˆç­‰å¾… 2 å°æ™‚æ‰èƒ½å†æ¬¡é€²è¡Œ YouTube ä¸‹è¼‰"
premium_required_description = "å¦‚æœæ˜¯å…è²»ç‰ˆä½¿ç”¨è€…ï¼Œå¿…é ˆç­‰å¾… 2 å°æ™‚æ‰èƒ½å†æ¬¡é€²è¡Œ HLS ä¸‹è¼‰"
v9_key_migration_failed_title = "æˆæ¬Šæ›´æ–°å¤±æ•—"
v9_key_migration_failed_description = "æ›´æ–°æˆæ¬Šæ™‚ç™¼ç”Ÿå•é¡Œã€‚è«‹å˜—è©¦æ¢å¾©è³¼è²·ã€‚"

# Downloading media box
stop = "åœæ­¢" # For HLS downloads
cancel = "å–æ¶ˆ" # For HTTP downloads

# Media we found in the page
copy_url = "è¤‡è£½ URL" # In menu and as a button
always_copy_url = "ä¸€å¾‹è¤‡è£½ URL"
download_button = "ä¸‹è¼‰"
download_audio_button = "è²éŸ³"
download_audio_and_video_menu = "ä¸‹è¼‰è²éŸ³å’Œå½±ç‰‡"
download_audio_only_menu = "åªä¸‹è¼‰è²éŸ³"
audio_only_for_this_website = "é‡å°æ­¤ç¶²ç«™ä¸€å¾‹åªä¸‹è¼‰è²éŸ³"
details = "è©³ç´°è³‡è¨Š"
more_settings = "æ›´å¤šè¨­å®šâ€¦"

# Report buttons
report = "å›å ±"
reporting = "æ­£åœ¨å›å ±â€¦"
reported = "å·²å›å ±"

# Video not playing - page
not_playing_title = "ç„¡æ³•æ’­æ”¾å½±ç‰‡ï¼Ÿ"
not_playing_broken_title = "è²éŸ³æˆ–å½±ç‰‡æ¯€æï¼Ÿ"
not_playing_broken_description = "è«‹å›å ±å¤±æ•—çš„åª’é«”ã€‚æˆ‘å€‘å°‡ç›¡åŠ›æ‰¾å‡ºå¤±æ•—çš„åŸå›  (æˆ‘å€‘ä»¥åŒ¿åæ–¹å¼ï¼Œå‚³é€å½±ç‰‡ URLï¼ä¸æœƒè¿½è¹¤æ‚¨ï¼)"
not_playing_broken_solution_title = "å˜—è©¦ä½¿ç”¨ç¾ä»£å½±ç‰‡æ’­æ”¾å™¨"
not_playing_broken_solution_windows_1 = "æˆ‘å€‘æ¨è–¦ VLCï¼š"
not_playing_broken_solution_mac_1 = "æˆ‘å€‘æ¨è–¦ IINAï¼š"
not_playing_broken_solution_2 = "å®ƒæ˜¯ç¾ä»£ã€å®‰å…¨çš„é–‹æ”¾åŸå§‹ç¢¼è»Ÿé«”ã€‚"
not_playing_default_player = "ç¢ºå®šå·²å°‡æ‚¨çš„å½±ç‰‡æ’­æ”¾å™¨ï¼Œè¨­ç‚ºç³»çµ±é è¨­å½±ç‰‡æ’­æ”¾å™¨"
not_playing_default_player_solution_windows = "åœ¨ Windows çš„ã€Œæ§åˆ¶å°ã€ä¸­ï¼ŒæŒ‰ä¸€ä¸‹ã€Œé è¨­ç¨‹å¼ã€ï¼Œç„¶å¾Œè®Šæ›´æ’­æ”¾å™¨çš„é è¨­ç¨‹å¼ã€‚"
not_playing_default_player_solution_mac = "é–‹å•Ÿä¸‹è¼‰ç›®éŒ„ï¼Œåœ¨å½±ç‰‡æª”æ¡ˆä¸ŠæŒ‰ä¸€ä¸‹æ»‘é¼ å³éµã€‚æŒ‰ä¸€ä¸‹ã€Œå–å¾—è³‡è¨Šã€ã€‚åœ¨ã€Œé–‹å•Ÿæ–¹å¼ã€å€åŸŸä¸­ï¼Œé¸æ“‡ IINAã€‚æŒ‰ä¸€ä¸‹ã€Œå…¨éƒ¨è®Šæ›´ã€æŒ‰éˆ•ã€‚"

[web]

# On top of all pages.
header_help = "èªªæ˜"
header_community = "ç¤¾ç¾¤"

# Context: activation page after receiving the magic link via email.
activate_title = "å•Ÿç”¨" # hope it crashes
activate_pending = "ç­‰å¾…ä¸­â€¦"
activate_success = "æˆåŠŸ"
activate_error = "éŒ¯èª¤"
activate_no_addon_found = "æ‰¾ä¸åˆ°é™„åŠ å…ƒä»¶ã€‚æ˜¯å¦å·²å®‰è£é™„åŠ å…ƒä»¶ï¼Ÿ"
activate_no_method_found = "æ‰¾ä¸åˆ°æ–¹æ³•ã€‚"
activate_help_me = "å”åŠ©æˆ‘ã€‚"

# Context: webpage to restore a purchase, which require the user to enter their email.
issue_title = "æ­£åœ¨æ¢å¾©è³¼è²·"
issue_submit = "æäº¤"
issue_thank_you = "è¬è¬"
issue_enter_email = "è‹¥è¦æ¢å¾©è³¼è²·ï¼Œè«‹è¼¸å…¥ç”¨ä»¥è³¼è²·æˆæ¬Šçš„é›»å­éƒµä»¶åœ°å€ï¼š"
issue_email_sent = "æˆ‘å€‘å·²å‚³é€é›»å­éƒµä»¶çµ¦æ‚¨ï¼Œå…¶ä¸­åŒ…å«å¯å•Ÿç”¨ç”¢å“çš„é€£çµã€‚"
issue_or_digit = "æˆ–è€…ï¼Œæ‚¨ä¹Ÿå¯ä»¥è¼¸å…¥æˆ‘å€‘å‚³é€çµ¦æ‚¨çš„ 6 ä½æ•¸ä»£ç¢¼ï¼š"

# Context: this page - https://downloadhelper.net/
landing_text1 = "å¾ä»»ä½•ç¶²ç«™ä¸‹è¼‰ä»»ä½•å½±ç‰‡ï¼Œå°±æ˜¯é€™éº¼å¥½ç”¨ï¼"
landing_text2 = "æ”¯æ´ 1000 å¤šå€‹ç¶²ç«™"
landing_text3 = "å— 700 è¬ä½¿ç”¨è€…ä¿¡ä»»"
landing_text4 = "æ“´å……åŠŸèƒ½å•†åº—è©•åƒ¹ 4.5 é¡†æ˜Ÿ"
landing_install_for_google = "ç‚º Chrome å®‰è£"
landing_install_for_mozilla = "ç‚º Firefox å®‰è£"
landing_install_for_microsoft = "ç‚º Edge å®‰è£"
landing_feature1_title = "å…¨é€Ÿ HD ä¸‹è¼‰"
landing_feature1_description = "ä»¥æœ€é«˜é€Ÿåº¦ä¸‹è¼‰é«˜ç•«è³ªå½±ç‰‡ã€‚æˆ‘å€‘ä»¥æ“æœ‰æœ€å¿«é€Ÿçš„ä¸‹è¼‰å¼•æ“ç‚ºå‚²ã€‚"
landing_feature2_title = "å°å­˜å½±ç‰‡"
landing_feature2_description = "å°å­˜æ‚¨å–œæ„›çš„å½±ç‰‡ï¼Œç¢ºä¿çµ•ä¸éºå¤±ã€‚"
landing_feature3_title = "ç›´æ’­æ”¯æ´"
landing_feature3_description = "é›¢ç·šè§€çœ‹ç›´æ’­ï¼Œæ“ºè„«å³æ™‚é™åˆ¶ã€‚"
landing_feature4_title = "è²éŸ³ä¸‹è¼‰"
landing_feature4_description = "å¾å½±ç‰‡ä¸­æ“·å–è²éŸ³ï¼Œè½‰æ›æˆ MP3 æˆ– podcast ä»¥æ–¹ä¾¿æ”¶è½ã€‚"

# Context: this is for a "è³¼è²·æˆæ¬Š" webpage.
premium_hero1 = "ä»˜è²»ä¸€æ¬¡ï¼Œæ°¸ä¹…ä½¿ç”¨"
premium_hero2 = "å–å¾— Video DownloadHelper çµ‚èº«æˆæ¬Š"
premium_hero3 = "ç›¡æƒ…ä¸‹è¼‰ä»»ä½•å½±ç‰‡ï¼Œä¸å—é™åˆ¶ã€‚"
