# Chinese

[addon]

# Video DownloadHelper description. 132 characters max.
appDesc = "ä»ç½‘ä¸Šä¸‹è½½è§†é¢‘ã€‚"

# Global strings
restore_purchase_button = "æ¢å¤è´­ä¹°"
get_premium_button = "è·å–é«˜çº§ä¼šå‘˜"
back = "è¿”å›" # Go back button - in Settings panel for example

# Strings for the main panel
waiting_for_media = "ç­‰å¾…åª’ä½“â€¦"
nomedia_title = "çœ‹ä¸åˆ°æŸ¥æ‰¾çš„åª’ä½“ï¼Ÿ"
nomedia_description = "æ’­æ”¾è§†é¢‘ï¼ˆå¦‚æœ‰å¹¿å‘Šè¯·è·³è¿‡ï¼‰ï¼Œä»¥å¸®åŠ©æ£€æµ‹åª’ä½“ã€‚æˆ–æŠ¥å‘Šåª’ä½“ç¼ºå¤±ã€‚"
nomedia_reload_button = "å¼ºåˆ¶æ£€æµ‹"
nomedia_reload_button_tooltip = "å¼ºåˆ¶é‡æ–°åŠ è½½é¡µé¢ï¼ˆæ¸…é™¤ cookieï¼‰"
show_nomedia_button = "æ— è§†é¢‘ï¼Ÿ"
show_nomedia_button_tooltip = "å¦‚æœæ‰¾ä¸åˆ°æ‚¨çš„è§†é¢‘ï¼Œè¯·å•å‡»æ­¤å¤„"
setting_button_tooltip = "è®¾ç½®"
history_button_tooltip = "æ˜¾ç¤ºä¸‹è½½å†å²"
translate_button_tooltip = "å¸®åŠ©è½¬æ¢ VDH"

# Downloaded media box
open_source_tab_button_tooltip = "æ‰“å¼€æºé€‰é¡¹å¡"
retry_download_button_tooltip = "é‡è¯•ä¸‹è½½"
delete_file_button_tooltip = "åˆ é™¤æ–‡ä»¶"
download_directory_button_tooltip = "æ˜¾ç¤ºä¸‹è½½ç›®å½•"
show_in_popup_button_tooltip = "åœ¨å¼¹å‡ºçª—å£ä¸­æ˜¾ç¤º"
show_in_sidebar_button_tooltip = "åœ¨ä¾§è¾¹æ ä¸­æ˜¾ç¤º"
video_not_playing_button_tooltip = "è§†é¢‘æ— æ³•æ’­æ”¾ï¼Ÿ"
play = "æ’­æ”¾"
warn_drm_tooltip = "æ£€æµ‹åˆ° DRM"

# Strings for the settings panel.
version_title = "ç‰ˆæœ¬"
account_title = "å¸æˆ·"
leave_review_description = "æ‚¨å¥½ ğŸ¤šï¼ŒVideo DownloadHelper å¯å…è´¹ä½¿ç”¨ã€‚æ‚¨ä»‹æ„ç»™ä¸ªå¥½è¯„å—ï¼Ÿè¿™å¯¹æˆ‘ä¼šæœ‰å¾ˆå¤§å¸®åŠ© ğŸ˜Šã€‚"
leave_review_button = "ç•™ä¸‹è¯„è®º"
account_status= "çŠ¶æ€"
account_status_premium = "é«˜çº§ä¼šå‘˜ï¼ˆ$1ï¼‰" # $1 is the store (Mozilla, Google, Microsoft, All)
free_account = "å…è´¹å¥—é¤"
copy_to_clipboard = "å°†ä¿¡æ¯å¤åˆ¶åˆ°å‰ªè´´æ¿"
my_account_button = "æˆ‘çš„å¸æˆ·"
download_title = "ä¸‹è½½å†…å®¹"
show_notification = "ä¸‹è½½å®Œæˆåæ˜¾ç¤ºé€šçŸ¥"
max_parallel_downloads = "æœ€å¤§å¹¶è¡Œä¸‹è½½æ•°"
change_download_directory = "æ›´æ”¹ä¸‹è½½ç›®å½•"

private_browsing_title = "éšç§æµè§ˆ"
private_browsing_warning = "Video DownloadHelper åœ¨éšç§æµè§ˆæ¨¡å¼ä¸‹æœªå¯ç”¨ã€‚"
private_browsing_notifications = "æ˜¾ç¤ºéšç§ä¸‹è½½é€šçŸ¥"
private_browsing_button = "æ›´æ”¹éšç§æµè§ˆè®¾ç½®"
prefer_original_audio = "é¦–é€‰åŸå§‹éŸ³é¢‘" # Firefox only
prefer_hls = "é¦–é€‰ HLS" # Firefox only
settings_history_title = "å†å²è®°å½•"
history_description = "è®°ä½ä¸‹è½½ä¿¡æ¯"
history_limit = "å¿˜è®°ä¸‹è½½ä¿¡æ¯å‰çš„å¤©æ•°"
appearance_title = "å¤–è§‚"
theme_title = "ä¸»é¢˜"
theme_light = "æµ…è‰²ä¸»é¢˜"
theme_dark = "æ·±è‰²ä¸»é¢˜"
theme_system = "ç³»ç»Ÿä¸»é¢˜"
popup_size_title = "çª—å£å¤§å°"
popup_size_small = "å°"
popup_size_medium = "ä¸­"
popup_size_big = "å¤§"
panel_position_title = "é¢æ¿ä½ç½®"
use_popup = "ä½¿ç”¨å¼¹å‡ºçª—å£"
use_sidebar = "ä½¿ç”¨ä¾§è¾¹æ "
behavior_title = "è¡Œä¸º"
show_in_context_menu = "åœ¨é¡µé¢å³é”®èœå•ä¸­æ˜¾ç¤ºä¸‹è½½èœå•"
restart_addon = "é‡æ–°å¯åŠ¨æ’ä»¶"
reset_settings = "é‡ç½®è®¾ç½®"
prefer_highest_quality = "é»˜è®¤é€‰æ‹©å¯è¾¾åˆ°çš„æœ€é«˜ç”»è´¨ï¼Œè€Œé 1080pï¼ˆä¸‹è½½é€Ÿåº¦è¾ƒæ…¢ï¼Œç”»è´¨æ›´é«˜ï¼‰ã€‚"

# String for history page
history_title = "ä¸‹è½½å†å²"
history_warning = "æˆ‘ä»¬ä¸ä¼šè®°å½•æ‚¨çš„ä¸‹è½½å†å²ã€‚æ‚¨æ˜¯å¦å¸Œæœ› Video DownloadHelper è®°ä½æ‚¨çš„ä¸‹è½½å†å²ï¼Ÿ"
history_warning_2 = "åˆ«æ‹…å¿ƒï¼Œæ‰€æœ‰å†…å®¹éƒ½ä¼šä¿å­˜åœ¨æ‚¨çš„è®¾å¤‡ä¸Šã€‚æˆ‘ä»¬éå¸¸é‡è§†æ‚¨çš„éšç§ã€‚"
enable_history = "å¯ç”¨å†å²è®°å½•"
clear_history = "æ¸…é™¤å†å²è®°å½•"
disable_history = "ç¦ç”¨å†å²è®°å½•"
no_downloads_yet = "å°šæ— ä¸‹è½½å†…å®¹ã€‚"

# Various notifications
download_failed = "ä¸‹è½½å¤±è´¥ã€‚"
download_failed_description = "å‡ºé”™äº†ã€‚è¯·æŠ¥å‘Šé”™è¯¯ï¼Œæˆ‘ä»¬å°†å°½æœ€å¤§åŠªåŠ›æŸ¥æ‰¾é”™è¯¯åŸå› ï¼ˆæˆ‘ä»¬ä¼šä»¥åŒ¿åå½¢å¼å‘é€è§†é¢‘ URLï¼Œç»ä¸ä¼šè·Ÿè¸ªæ‚¨ï¼ï¼‰"
download_with_drm_failed_description = "å‡ºé”™äº†ã€‚æˆ‘ä»¬è®¤ä¸ºæ­¤è§†é¢‘é‡‡ç”¨äº† DRM ä¿æŠ¤ã€‚æˆ‘ä»¬ä¸æ”¯æŒé‡‡ç”¨ DRM ä¿æŠ¤çš„è§†é¢‘ã€‚"
no_youtube = "ä¸å…è®¸ä» youtube ä¸‹è½½"
no_youtube_description = "å¾ˆé—æ†¾ï¼ŒChrome åº”ç”¨å•†åº—ä¸å…è®¸æ‰©å±•ç¨‹åºä¸‹è½½ YouTube è§†é¢‘ã€‚Firefox ç­‰å…¶ä»–æµè§ˆå™¨æ— æ­¤é™åˆ¶ã€‚"
premium_required = "éœ€è¦é«˜çº§ä¼šå‘˜çŠ¶æ€ã€‚"
premium_yt_required_description = "å¦‚æœæ²¡æœ‰é«˜çº§ä¼šå‘˜çŠ¶æ€ï¼ŒYouTube è§†é¢‘ä¸‹è½½åœ¨ä¸Šä¸€æ¬¡ä¸‹è½½å®Œæˆ 2 å°æ—¶åæ‰èƒ½è¿›è¡Œã€‚"
premium_required_description = "å¦‚æœæ²¡æœ‰é«˜çº§ä¼šå‘˜çŠ¶æ€ï¼ŒHLS è§†é¢‘ä¸‹è½½åœ¨ä¸Šä¸€æ¬¡ä¸‹è½½å®Œæˆ 2 å°æ—¶åæ‰èƒ½è¿›è¡Œã€‚"
v9_key_migration_failed_title = "è®¸å¯è¯å‡çº§å¤±è´¥"
v9_key_migration_failed_description = "æˆ‘ä»¬åœ¨å‡çº§æ‚¨çš„è®¸å¯è¯æ—¶é‡åˆ°äº†é—®é¢˜ã€‚è¯·å°è¯•æ¢å¤æ‚¨çš„è´­ä¹°ã€‚"

# Downloading media box
stop = "åœæ­¢" # For HLS downloads
cancel = "å–æ¶ˆ" # For HTTP downloads

# Media we found in the page
copy_url = "å¤åˆ¶ URL" # In menu and as a button
always_copy_url = "å§‹ç»ˆå¤åˆ¶ URL"
download_button = "ä¸‹è½½"
download_audio_button = "éŸ³é¢‘"
download_audio_and_video_menu = "ä¸‹è½½éŸ³é¢‘å’Œè§†é¢‘"
download_audio_only_menu = "ä»…ä¸‹è½½éŸ³é¢‘"
audio_only_for_this_website = "æ­¤ç½‘ç«™å§‹ç»ˆåªä¸‹è½½éŸ³é¢‘"
details = "è¯¦ç»†ä¿¡æ¯"
more_settings = "æ›´å¤šè®¾ç½®â€¦"

# Report buttons
report = "æŠ¥å‘Š"
reporting = "æ­£åœ¨æŠ¥å‘Šâ€¦"
reported = "å·²æŠ¥å‘Š"

# Video not playing - page
not_playing_title = "è§†é¢‘æ— æ³•æ’­æ”¾ï¼Ÿ"
not_playing_broken_title = "éŸ³é¢‘æˆ–è§†é¢‘æŸåï¼Ÿ"
not_playing_broken_description = "æŠ¥å‘Šæ•…éšœåª’ä½“ã€‚æˆ‘ä»¬å°†å°½æœ€å¤§åŠªåŠ›æŸ¥æ‰¾é”™è¯¯åŸå› ï¼ˆæˆ‘ä»¬ä¼šä»¥åŒ¿åå½¢å¼å‘é€è§†é¢‘ URLï¼Œç»ä¸ä¼šè·Ÿè¸ªæ‚¨ï¼ï¼‰"
not_playing_broken_solution_title = "å°è¯•ä½¿ç”¨ç°ä»£è§†é¢‘æ’­æ”¾å™¨"
not_playing_broken_solution_windows_1 = "å»ºè®®ä½¿ç”¨ VLCï¼š"
not_playing_broken_solution_mac_1 = "å»ºè®®ä½¿ç”¨ IINAï¼š"
not_playing_broken_solution_2 = "è¿™æ˜¯ä¸€æ¬¾ç°ä»£ã€å®‰å…¨ã€å¼€æºçš„æ’­æ”¾å™¨ã€‚"
not_playing_default_player = "ç¡®ä¿æ‚¨çš„è§†é¢‘æ’­æ”¾å™¨è®¾ä¸ºæ‚¨çš„ç³»ç»Ÿé»˜è®¤è§†é¢‘æ’­æ”¾å™¨ã€‚"
not_playing_default_player_solution_windows = "åœ¨ Windows çš„\"æ§åˆ¶é¢æ¿\"ä¸­ï¼Œå•å‡» \"é»˜è®¤ç¨‹åº\"ï¼Œç„¶åæ›´æ”¹æ’­æ”¾å™¨çš„é»˜è®¤ç¨‹åºã€‚"
not_playing_default_player_solution_mac = "æ‰“å¼€ä¸‹è½½ç›®å½•å¹¶å³é”®å•å‡»è§†é¢‘æ–‡ä»¶ã€‚å•å‡»â€œè·å–ä¿¡æ¯â€ã€‚åœ¨â€œæ‰“å¼€æ–¹å¼â€éƒ¨åˆ†ï¼Œé€‰æ‹© IINAã€‚å•å‡»â€œå…¨éƒ¨æ›´æ”¹â€æŒ‰é’®ã€‚"

[web]

# On top of all pages.
header_help = "å¸®åŠ©"
header_community = "ç¤¾åŒº"

# Context: activation page after receiving the magic link via email.
activate_title = "æ¿€æ´»" # hope it crashes
activate_pending = "å¾…å¤„ç†â€¦"
activate_success = "æˆåŠŸ"
activate_error = "é”™è¯¯"
activate_no_addon_found = "æœªæ‰¾åˆ°æ’ä»¶ã€‚æ’ä»¶æ˜¯å¦å·²å®‰è£…ï¼Ÿ"
activate_no_method_found = "æœªæ‰¾åˆ°æ–¹æ³•ã€‚"
activate_help_me = "å¸®å¸®æˆ‘ã€‚"

# Context: webpage to restore a purchase, which require the user to enter their email.
issue_title = "æ­£åœ¨æ¢å¤è´­ä¹°"
issue_submit = "æäº¤"
issue_thank_you = "æ„Ÿè°¢"
issue_enter_email = "è¦æ¢å¤è´­ä¹°ï¼Œè¯·è¾“å…¥æ‚¨è´­ä¹°è®¸å¯è¯æ—¶ä½¿ç”¨çš„ç”µå­é‚®ç®±åœ°å€ï¼š"
issue_email_sent = "æˆ‘ä»¬åˆšåˆšå‘æ‚¨å‘é€ä¸€å°ç”µå­é‚®ä»¶ï¼Œå…¶ä¸­åŒ…å«æ‚¨äº§å“çš„æ¿€æ´»é“¾æ¥ã€‚"
issue_or_digit = "æ‚¨ä¹Ÿå¯ä»¥è¾“å…¥æˆ‘ä»¬å‘ç»™æ‚¨çš„ 6 ä½ä»£ç ã€‚"

# Context: this page - https://downloadhelper.net/
landing_text1 = "å¯ä»¥ä»ä»»ä½•ç½‘ç«™ä¸‹è½½ä»»ä½•è§†é¢‘ï¼"
landing_text2 = "æ”¯æŒ 1000 å¤šä¸ªç½‘ç«™"
landing_text3 = "å—åˆ° 700 å¤šä¸‡ç”¨æˆ·çš„ä¿¡èµ–"
landing_text4 = "åœ¨æ‰©å±•ç¨‹åºå•†åº—è·å¾— 4.5 æ˜Ÿè¯„åˆ†"
landing_install_for_google = "ä¸º Chrome å®‰è£…"
landing_install_for_mozilla = "ä¸º Firefox å®‰è£…"
landing_install_for_microsoft = "ä¸º Edge å®‰è£…"
landing_feature1_title = "å…¨é€Ÿä¸‹è½½é«˜æ¸…è§†é¢‘"
landing_feature1_description = "ä»¥æœ€é«˜é€Ÿåº¦ä¸‹è½½é«˜æ¸…è§†é¢‘ã€‚æˆ‘ä»¬è‡ªè±ªåœ°å®£å¸ƒï¼Œæˆ‘ä»¬æ‹¥æœ‰ç›®å‰å¸‚é¢ä¸Šé€Ÿåº¦æœ€å¿«çš„ä¸‹è½½å¼•æ“ã€‚"
landing_feature2_title = "å­˜æ¡£è§†é¢‘"
landing_feature2_description = "å°†æ‚¨å–œçˆ±çš„è§†é¢‘å­˜æ¡£ï¼Œç¡®ä¿ä¸ä¼šé—å¤±ä»»ä½•å†…å®¹ã€‚"
landing_feature3_title = "æ”¯æŒç›´æ’­"
landing_feature3_description = "äº«å—ç¦»çº¿è§‚çœ‹ç›´æ’­ï¼Œæ‘†è„±å®æ—¶è§‚çœ‹çš„é™åˆ¶ã€‚"
landing_feature4_title = "éŸ³é¢‘ä¸‹è½½"
landing_feature4_description = "ä»è§†é¢‘ä¸­æå–éŸ³é¢‘ï¼Œå°†å…¶è½¬æ¢ä¸º MP3 æˆ–æ’­å®¢ï¼Œæ–¹ä¾¿æ”¶å¬ã€‚"

# Context: this is for a "è´­ä¹°è®¸å¯è¯" webpage.
premium_hero1 = "ä¸€æ¬¡ä»˜æ¬¾ï¼Œæ°¸ä¹…ä½¿ç”¨"
premium_hero2 = "è·å– Video DownloadHelper çš„ç»ˆèº«è®¸å¯è¯ã€‚"
premium_hero3 = "éšå¿ƒæ‰€æ¬²ä¸‹è½½è§†é¢‘ï¼Œæ²¡æœ‰ä»»ä½•é™åˆ¶ã€‚"
